### ISSUE TITLE
wireguard-webadmin will not start

### ISSUE THREAD

**Issue by renfie** [eduardogsilva/wireguard_webadmin#1]
The container wireguard-webadmin will not start and show's the following error:

`File "/app/wireguard_webadmin/settings.py", line 130, in <module>
    from wireguard_webadmin.production_settings import *
ModuleNotFoundError: No module named 'wireguard_webadmin.production_settings'`

**Comment by eduardogsilva** [comment]
Hello there!

Thank you for bringing this to my attention. To properly configure the user settings in Django, you will need to manually create the `wireguard_webadmin/production_settings.py` file and configure the minimum required variables as outlined below:

```python
DEBUG = False
ALLOWED_HOSTS = ['your_domain']
CSRF_TRUSTED_ORIGINS = ['https://your_domain']
SECRET_KEY = 'your_secret_key'
```

Additionally, there's one more essential step: placing the SSL certificates for the virtual host in Nginx.

I'll keep this issue open since I plan to enhance the production settings based on your feedback and further refinements.

If you have any more questions or suggestions on how I can improve our production setup, please feel free to share. If you find any other issues, please let me know.

Thanks for reporting this :)

btw, I'm planning to improve a lot of small details in the next few days.

**Comment by renfie** [comment]
Hi,

I have filled the production_settings.py. Under secret_key you have to add a random one or the nginx.key? If it doesn't matter, I used a local IP for testing purposes. I have copied the certificates to the correct position and renamed them.
It is also not the error message of the web server, but that of the Wireguard.

**Comment by eduardogsilva** [comment]
Those settings in the file wireguard_webadmin/production_settings.py are just for Django. You can omit the SECRET_KEY if its just for testing purposes only. It's designed to keep your web sessions secure.
Anyway, I will work today to remove this step from the deployment steps. ;)


If you are having issues starting the wireguard, please open a new issue detailing the problem.

Cheers!

**Comment by renfie** [comment]
That's the wireguard container not wireguard-webadmin-nginx!
Here is tho hole log:

`2024-02-16T12:10:16.888763624Z Traceback (most recent call last):
2024-02-16T12:10:16.888869623Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
2024-02-16T12:10:16.889047936Z     self.execute(*args, **cmd_options)
2024-02-16T12:10:16.889085010Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
2024-02-16T12:10:16.889398303Z     output = self.handle(*args, **options)
2024-02-16T12:10:16.889422062Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 103, in wrapper
2024-02-16T12:10:16.889592430Z     saved_locale = translation.get_language()
2024-02-16T12:10:16.889614486Z   File "/usr/local/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 210, in get_language
2024-02-16T12:10:16.889812039Z     return _trans.get_language()
2024-02-16T12:10:16.889833132Z   File "/usr/local/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
2024-02-16T12:10:16.889984482Z     if settings.USE_I18N:
2024-02-16T12:10:16.890004871Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in __getattr__
2024-02-16T12:10:16.890158758Z     self._setup(name)
2024-02-16T12:10:16.890178721Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 76, in _setup
2024-02-16T12:10:16.890330589Z     self._wrapped = Settings(settings_module)
2024-02-16T12:10:16.890350219Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
2024-02-16T12:10:16.890530513Z     mod = importlib.import_module(self.SETTINGS_MODULE)
2024-02-16T12:10:16.890586124Z   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-02-16T12:10:16.890725326Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-02-16T12:10:16.890746363Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-02-16T12:10:16.890982305Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-02-16T12:10:16.891143618Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-02-16T12:10:16.891268172Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-02-16T12:10:16.891403708Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-02-16T12:10:16.891567003Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-02-16T12:10:16.891703001Z   File "/app/wireguard_webadmin/settings.py", line 130, in <module>
2024-02-16T12:10:16.891926295Z     from wireguard_webadmin.production_settings import *
2024-02-16T12:10:16.891948887Z ModuleNotFoundError: No module named 'wireguard_webadmin.production_settings'
2024-02-16T12:10:16.891963184Z 
2024-02-16T12:10:16.891976721Z During handling of the above exception, another exception occurred:
2024-02-16T12:10:16.891990535Z 
2024-02-16T12:10:16.892003850Z Traceback (most recent call last):
2024-02-16T12:10:16.892017220Z   File "/app/manage.py", line 22, in <module>
2024-02-16T12:10:16.892110423Z     main()
2024-02-16T12:10:16.892129108Z   File "/app/manage.py", line 18, in main
2024-02-16T12:10:16.892239533Z     execute_from_command_line(sys.argv)
2024-02-16T12:10:16.892258792Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
2024-02-16T12:10:16.892616751Z     utility.execute()
2024-02-16T12:10:16.892650510Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
2024-02-16T12:10:16.892928211Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2024-02-16T12:10:16.892949322Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 425, in run_from_argv
2024-02-16T12:10:16.893232059Z     connections.close_all()
2024-02-16T12:10:16.893253059Z   File "/usr/local/lib/python3.10/site-packages/django/utils/connection.py", line 84, in close_all
2024-02-16T12:10:16.893398576Z     for conn in self.all(initialized_only=True):
2024-02-16T12:10:16.893417280Z   File "/usr/local/lib/python3.10/site-packages/django/utils/connection.py", line 76, in all
2024-02-16T12:10:16.893560037Z     return [
2024-02-16T12:10:16.893579500Z   File "/usr/local/lib/python3.10/site-packages/django/utils/connection.py", line 73, in __iter__
2024-02-16T12:10:16.893707980Z     return iter(self.settings)
2024-02-16T12:10:16.893727647Z   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
2024-02-16T12:10:16.893876071Z     res = instance.__dict__[self.name] = self.func(instance)
2024-02-16T12:10:16.893896349Z   File "/usr/local/lib/python3.10/site-packages/django/utils/connection.py", line 45, in settings
2024-02-16T12:10:16.894014218Z     self._settings = self.configure_settings(self._settings)
2024-02-16T12:10:16.894032496Z   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 148, in configure_settings
2024-02-16T12:10:16.894206938Z     databases = super().configure_settings(databases)
2024-02-16T12:10:16.894226827Z   File "/usr/local/lib/python3.10/site-packages/django/utils/connection.py", line 50, in configure_settings
2024-02-16T12:10:16.894354122Z     settings = getattr(django_settings, self.settings_name)
2024-02-16T12:10:16.894373307Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in __getattr__
2024-02-16T12:10:16.894540713Z     self._setup(name)
2024-02-16T12:10:16.894560527Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 76, in _setup
2024-02-16T12:10:16.894704766Z     self._wrapped = Settings(settings_module)
2024-02-16T12:10:16.894724377Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
2024-02-16T12:10:16.894904024Z     mod = importlib.import_module(self.SETTINGS_MODULE)
2024-02-16T12:10:16.894924560Z   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-02-16T12:10:16.895134132Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-02-16T12:10:16.895161577Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-02-16T12:10:16.895270279Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-02-16T12:10:16.895398185Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-02-16T12:10:16.895534684Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-02-16T12:10:16.895657608Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-02-16T12:10:16.895794200Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-02-16T12:10:16.895917439Z   File "/app/wireguard_webadmin/settings.py", line 130, in <module>
2024-02-16T12:10:16.896121807Z     from wireguard_webadmin.production_settings import *
2024-02-16T12:10:16.896144548Z ModuleNotFoundError: No module named 'wireguard_webadmin.production_settings'`

**Comment by eduardogsilva** [comment]
Hello there! It's fixed/improved.

No need to handle with django settings anymore. Just clone the repository again and run: 

`SERVER_ADDRESS=yourserver.example.com docker-compose up --build -d
`
If you don't want/need nginx for https (not recommended), you can launch the project with:
`docker-compose -f docker-compose-no-nginx.yml up --build -d
`
Cheers!
